### ISSUE TITLE
Мокапы.

### ISSUE THREAD

**Issue by Martenfur** [AleksandrVolchkov550501/PJ-17#1]
Судя по мокапам, будет либо открыто два разных окна для списка контактов и диалога, либо окно приложения будет меняться. Это не круто. Совершенно не круто. Лучше объединить их в одно окно или что-то вроде того. 
Также, предложение фичи: полный временный мьют либо всех пользователей, либо отдельных. Скажем, я работаю с 16:00 до 20:00 и в это время не хочу получать ни от кого никаких сообщений, кроме моего напарника.

**Comment by AleksandrVolchkov550501** [comment]
Будет одно окно со списком контактов, и много окон с диалогами. Лично у меня не лежит душа к одному окну. Я хочу отдельно мониторить тех, кто онлайн, и отдельно общаться с каждым. Хотя, я еще подумаю над окном диалогов со вкладками. В общем, я поклонник стареньких мессенджеров. :) Об одном окне я буду думать в самом отдаленном будущем. )

Предложение фичи хорошее. :) Думаю, что можно сделать так: 
– При приходе сообщения от напарника появляется всплывашка с сообщением и висит такое-то время. По щелчку по ней левой кнопкой мыши, откроется окно диалога. По щелчку правой кнопкой мыши, всплывашка исчезает и сообщение считается прочитанным. При бездействии, всплывашка сворачивается в маленькую иконку у края экрана.
– При приходе сообщения от других контактов всплывашек не будет. Будет сразу появляться общая для всех иконка у края экрана, которая будет сигнализировать о том, что вообще имеются новые непрочитанные сообщения. О наличии сообщений от контакта также будет символизировать иконка с конвертом напротив имени контакта в списке контактов.
