### ISSUE TITLE
Функциональные требования и база данных.

### ISSUE THREAD

**Issue by BlackFox147** [AleksandrVolchkov550501/PJ-17#2]
Возможно, информацию о базе данных лучше перенести в Программные интерфейсы.
[ссылка](https://github.com/AleksandrVolchkov550501/PJ-17/commit/f32d89776aec5b5e822b1135892bfc19d2d6bd66#diff-04c6e90faac2675aa89e2176d2eec7d8R59)

**Comment by AleksandrVolchkov550501** [comment]
Тогда уж лучше переформулировать требование, без упоминания о БД. Вообще, гугление приводит меня к тому, что, если рассуждать о БД как о внешнем сервисе, то тогда это требование нужно относить в раздел Нефункциональные требования -> Внешние интерфейсы. Ну, то есть, все то, что мы описали в Программных интерфейсах должно относиться к Нефункциональным требованиям. :)

**Comment by BlackFox147** [comment]
А если совсем по-хорошему, то ещё и в Нефункциональные требования -> Ограничения. И там описать параметры производительности, влияющие на выбор платформы реализации и/или развертывания (протоколы, серверы приложений, баз данных). Но это совсем по-хорошему. Но системные требования это одно (они более жёсткие и техничные), а пользовательские - это другое (они в более свободной форме). 
И там тоже можно указать про использование базы данных, но уже не в такой конкретной форме, как нужно было бы в функциональных. 
Просто, если вообще нигде не указывать, что ты используешь базу данных для хранения, то это тоже не очень хорошо. Всё-таки, это важная часть архитектуры твоего приложения.
